#!/usr/bin/env python
#-*- coding: utf-8 -*-
#
# predictWithModel test_file model_file output_file
#
# Copyright (C) 2014 Sheng Liu - sliu96@jhmi.edu
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
#from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
import cPickle as pickle
import pandas as pd
from sklearn.externals import joblib

if not len(sys.argv)==4:
    print 'Usage: predictWithModel test_file model_file output_file\n'
    exit(1)

print 'loading test file'
mat=pd.read_table(sys.argv[1],header=None)
mat=mat.fillna(0)

print 'loading model'
rf=joblib.load(sys.argv[2])

fset=[3,4,5,6,7,8,9,10,11,12,13]

X=mat[fset].values

print 'Test size: ',X.shape

pred=rf.predict_proba(X)[:,0]

pred_out=open(sys.argv[3],"w")
i=0
for item in pred:
    print >>pred_out, str(mat[0].values[i])+'\t'+str(mat[1].values[i])+'\t'+str(mat[2].values[i])+'\t'+str(item)
    i=i+1

